# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJi2dTULt6OYafRWbwF8StrpOYEb-EPn
"""



import matplotlib.pyplot as plt
import numpy as np

# Tasodifiy nuqtalar yaratish
x = np.random.rand(50) * 10  # 0dan 10gacha bo'lgan tasodifiy qiymatlar
y = np.random.rand(50) * 10  # 0dan 10gacha bo'lgan tasodifiy qiymatlar

# Scatter grafiği
plt.figure(figsize=(8, 6))
plt.scatter(x, y, color='blue', label='Nuqtalar')
plt.title('Tasodifiy Nuqtalar Scatter Grafiki')
plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')
plt.legend()
plt.grid()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Ma'lumotlar
x = np.linspace(0, 10, 100)
y = np.sin(x)

# Grafikni yaratish
plt.plot(x, y)
plt.title('Sine Function')
plt.xlabel('X axis')
plt.ylabel('Y axis')

# Grafikni ko'rsatish
plt.show()